-- MySQL Script generated by MySQL Workbench
-- Mon May 25 08:17:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`module_groups` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`module_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`modules` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `module_group_id` INT NULL,
  `name` VARCHAR(100) NOT NULL,
  `route` VARCHAR(100) NOT NULL,
  `order` INT NOT NULL,
  `is_shown` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modules_module_groups_idx` (`module_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_modules_module_groups`
    FOREIGN KEY (`module_group_id`)
    REFERENCES `ecommerce`.`module_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`authorization_types` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`authorization_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `ecommerce`.`roles` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `status` INT NOT NULL COMMENT '0 = inactive,\n1 = active',
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`admins` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `status` INT NOT NULL COMMENT '0 = inactive, 1 = active',
  `last_login` TIMESTAMP NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admins_roles1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_admins_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ecommerce`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`authorizations` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`authorizations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `module_id` INT NOT NULL,
  `authorization_type_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_authorizations_roles1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_authorizations_modules1_idx` (`module_id` ASC) VISIBLE,
  INDEX `fk_authorizations_authorization_types1_idx` (`authorization_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_authorizations_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ecommerce`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authorizations_modules1`
    FOREIGN KEY (`module_id`)
    REFERENCES `ecommerce`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_authorizations_authorization_types1`
    FOREIGN KEY (`authorization_type_id`)
    REFERENCES `ecommerce`.`authorization_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`users` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email_verified_at` DATETIME NULL,
  `remember_token` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`user_points` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`user_points` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `balance` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_points_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_points_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`warehouses` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`warehouses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `is_active` INT NOT NULL COMMENT '0 = inactive,\n1 = active',
  `city` VARCHAR(100) NOT NULL,
  `province` VARCHAR(100) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`orders` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `warehouse_id` INT NOT NULL,
  `order_number` VARCHAR(45) NOT NULL COMMENT 'ORD-2026-524123',
  `status` INT NOT NULL COMMENT '1 = pending payment, \n2 = paid,\n3 = processing, \n4 = shipped,\n5 = delivered,\n6 = cancelled',
  `subtotal` DECIMAL(15,2) NOT NULL,
  `shipping_cost` DECIMAL(15,2) NOT NULL,
  `point_redeemed` INT NOT NULL,
  `point_earned` INT NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `buyer_name` VARCHAR(100) NOT NULL,
  `buyer_email` VARCHAR(100) NOT NULL,
  `buyer_phone` VARCHAR(20) NOT NULL,
  `shipping_address` TEXT NOT NULL,
  `shipping_note` TEXT NULL,
  `note` TEXT NULL,
  `paid_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_orders_warehouses1_idx` (`warehouse_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_warehouses1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `ecommerce`.`warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`point_transactions` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`point_transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `type` INT NOT NULL COMMENT '1 = earn,\n2 = redeem,\n3 = adjustment',
  `amount` INT NOT NULL,
  `description` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_point_transactions_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_point_transactions_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_point_transactions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_point_transactions_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerce`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`file_storages` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`file_storages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`categories`   +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` INT NULL,
  `name` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `sort_order` INT NOT NULL,
  `is_active` INT NOT NULL COMMENT '0 = inactive, \n1 = active',
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE,
  INDEX `fk_categories_file_storages1_idx` (`image` ASC) VISIBLE,
  CONSTRAINT `fk_categories_file_storages1`
    FOREIGN KEY (`image`)
    REFERENCES `ecommerce`.`file_storages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`brands` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`products` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `thumbnail` INT NULL,
  `name` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `features` TEXT NULL,
  `gender` INT NOT NULL COMMENT '1 = wanita\n2 = pria\n3 = unisex',
  `is_active` INT NOT NULL COMMENT '0 = inactive,\n1 = active',
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `slug_UNIQUE` (`slug` ASC) VISIBLE,
  INDEX `fk_products_categories1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_products_brands1_idx` (`brand_id` ASC) VISIBLE,
  INDEX `fk_products_file_storages1_idx` (`thumbnail` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ecommerce`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_brands1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `ecommerce`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_file_storages1`
    FOREIGN KEY (`thumbnail`)
    REFERENCES `ecommerce`.`file_storages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`product_images`   +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `path` INT NOT NULL,
  `sort_order` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_images_products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_product_images_file_storages1_idx` (`path` ASC) VISIBLE,
  CONSTRAINT `fk_product_images_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerce`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_images_file_storages1`
    FOREIGN KEY (`path`)
    REFERENCES `ecommerce`.`file_storages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`product_variants` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`product_variants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `label` VARCHAR(100) NOT NULL,
  `price` DECIMAL(15,2) NOT NULL,
  `sku` VARCHAR(45) NOT NULL,
  `is_active` INT NOT NULL COMMENT '0 = inactive,\n1 = active',
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_variants_products1_idx` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `sku_UNIQUE` (`sku` ASC) VISIBLE,
  CONSTRAINT `fk_product_variants_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerce`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`warehouse_stocks` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`warehouse_stocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `warehouse_id` INT NOT NULL,
  `product_variant_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_warehouse_stocks_warehouses1_idx` (`warehouse_id` ASC) VISIBLE,
  INDEX `fk_warehouse_stocks_product_variants1_idx` (`product_variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_warehouse_stocks_warehouses1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `ecommerce`.`warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warehouse_stocks_product_variants1`
    FOREIGN KEY (`product_variant_id`)
    REFERENCES `ecommerce`.`product_variants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`promotions`   +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`promotions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `type` INT NOT NULL COMMENT '1 = flash sales',
  `is_active` INT NOT NULL COMMENT '0 = inactive,\n1 = active',
  `start_at` DATETIME NOT NULL,
  `end_at` DATETIME NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`promotion_items` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`promotion_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `promotion_id` INT NOT NULL,
  `product_variant_id` INT NOT NULL,
  `override_price` DECIMAL(15,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_promotion_items_promotions1_idx` (`promotion_id` ASC) VISIBLE,
  INDEX `fk_promotion_items_product_variants1_idx` (`product_variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_promotion_items_promotions1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `ecommerce`.`promotions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_promotion_items_product_variants1`
    FOREIGN KEY (`product_variant_id`)
    REFERENCES `ecommerce`.`product_variants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`order_items`  +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_variant_id` INT NOT NULL,
  `promotion_id` INT NULL,
  `product_name` VARCHAR(100) NOT NULL,
  `variant_label` VARCHAR(100) NOT NULL,
  `unit_price` DECIMAL(15,2) NOT NULL,
  `quantity` INT NOT NULL,
  `subtotal` DECIMAL(15,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_items_orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_items_product_variants1_idx` (`product_variant_id` ASC) VISIBLE,
  INDEX `fk_order_items_promotions1_idx` (`promotion_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerce`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_product_variants1`
    FOREIGN KEY (`product_variant_id`)
    REFERENCES `ecommerce`.`product_variants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_promotions1`
    FOREIGN KEY (`promotion_id`)
    REFERENCES `ecommerce`.`promotions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`payment_accounts` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`payment_accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bank_name` VARCHAR(100) NOT NULL,
  `account_number` VARCHAR(100) NOT NULL,
  `account_name` VARCHAR(100) NOT NULL,
  `is_active` INT NOT NULL COMMENT '0 = inactive,\n1 = active',
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`payments` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `payment_account_id` INT NOT NULL,
  `approved_by` INT NULL,
  `rejected_by` INT NULL,
  `proof_path` INT NULL,
  `amount` DECIMAL(15,2) NOT NULL,
  `status` INT NOT NULL COMMENT '1 = pending,\n2 = paid,\n3 = failed\n4 = expired',
  `rejected_reason` TEXT NULL,
  `approved_at` DATETIME NULL,
  `rejected_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payments_orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_payments_payment_accounts1_idx` (`payment_account_id` ASC) VISIBLE,
  INDEX `fk_payments_admins1_idx` (`approved_by` ASC) VISIBLE,
  INDEX `fk_payments_admins2_idx` (`rejected_by` ASC) VISIBLE,
  INDEX `fk_payments_file_storages1_idx` (`proof_path` ASC) VISIBLE,
  CONSTRAINT `fk_payments_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerce`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_payment_accounts1`
    FOREIGN KEY (`payment_account_id`)
    REFERENCES `ecommerce`.`payment_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_admins1`
    FOREIGN KEY (`approved_by`)
    REFERENCES `ecommerce`.`admins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_admins2`
    FOREIGN KEY (`rejected_by`)
    REFERENCES `ecommerce`.`admins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_file_storages1`
    FOREIGN KEY (`proof_path`)
    REFERENCES `ecommerce`.`file_storages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`carts` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_variant_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carts_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_carts_product_variants1_idx` (`product_variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_carts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_product_variants1`
    FOREIGN KEY (`product_variant_id`)
    REFERENCES `ecommerce`.`product_variants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`shipments` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`shipments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `warehouse_id` INT NOT NULL,
  `shipping_cost` DECIMAL(15,2) NOT NULL,
  `status` INT NOT NULL COMMENT '1 = pending, \n2 = picked up,\n3 = in transit,\n4 = out for delivery,\n5 = delivered,\n6 = failed',
  `courier_name` VARCHAR(100) NULL,
  `tracking_number` VARCHAR(100) NULL,
  `delivered_at` DATETIME NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shipments_orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_shipments_warehouses1_idx` (`warehouse_id` ASC) VISIBLE,
  CONSTRAINT `fk_shipments_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `ecommerce`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipments_warehouses1`
    FOREIGN KEY (`warehouse_id`)
    REFERENCES `ecommerce`.`warehouses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`shipment_tracking_logs`  +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`shipment_tracking_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shipment_id` INT NOT NULL,
  `updated_by` INT NOT NULL,
  `status` INT NOT NULL COMMENT '1 = pending, \n2 = picked up,\n3 = in transit,\n4 = out for delivery,\n5 = delivered,\n6 = failed',
  `note` TEXT NULL,
  `location` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shipment_tracking_logs_shipments1_idx` (`shipment_id` ASC) VISIBLE,
  INDEX `fk_shipment_tracking_logs_admins1_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_shipment_tracking_logs_shipments1`
    FOREIGN KEY (`shipment_id`)
    REFERENCES `ecommerce`.`shipments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipment_tracking_logs_admins1`
    FOREIGN KEY (`updated_by`)
    REFERENCES `ecommerce`.`admins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`reviews` +
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `order_item_id` INT NOT NULL,
  `rating` INT NOT NULL,
  `reason` TEXT NULL,
  `is_visible` INT NOT NULL COMMENT '0 = hide,\n1 = visible',
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reviews_order_items1_idx` (`order_item_id` ASC) VISIBLE,
  INDEX `fk_reviews_products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_reviews_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reviews_order_items1`
    FOREIGN KEY (`order_item_id`)
    REFERENCES `ecommerce`.`order_items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerce`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
